#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-jellyfin
- name: Ensure apt-transport-https and ca-certificates are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: yes

- name: Add Jellyfin GPG key
  ansible.builtin.apt_key:
    url: "{{ jellyfin_apt_key_url }}"
    state: present

- name: Add Jellyfin APT repository
  ansible.builtin.apt_repository:
    repo: "{{ jellyfin_apt_repo | replace('bullseye', jellyfin_debian_codename) }}"
    state: present
    filename: jellyfin

- name: Update apt cache after adding Jellyfin repo
  ansible.builtin.apt:
    update_cache: yes
  when: jellyfin_apt_repo is defined

- name: Install Jellyfin package
  ansible.builtin.apt:
    name: "{{ jellyfin_package }}"
    state: latest

- name: Ensure Jellyfin is enabled and started
  ansible.builtin.service:
    name: "{{ jellyfin_service }}"
    enabled: yes
    state: started