#SPDX-License-Identifier: MIT-0
---
# handlers file for ansible-role-jellyfin
- name: Reload systemd
  ansible.builtin.command: systemctl daemon-reload
  become: true

- name: Restart Jellyfin
  ansible.builtin.service:
    name: "{{ jellyfin_service }}"
    state: restarted